version: '3.8'

networks:
  net_decisionminds_api:
    name: net_decisionminds_api
    driver: bridge

services:

  nginx:
    container_name: c-${SUFIX}nginx
    hostname: h-${SUFIX}nginx
    build:
      context: ./docker/image/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - net_decisionminds_api
    ports:
      - 5000:80
    volumes:
      - ./:/var/www/html

  postgres:
    container_name: c-${SUFIX}postgres
    hostname: h-${SUFIX}postgres
    image: onixseven/postgresql:latest
    networks:
      - net_decisionminds_api
    ports:
      - 5001:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWD}
    volumes:
      - ./docker/volume/postgres:/var/lib/postgresql/data
